# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  durantyoungertrust-app:
    image: durantyoungertrust
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://durantyoungertrust-mysql:3306/durantyoungertrust?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://durantyoungertrust-mysql:3306/durantyoungertrust?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  durantyoungertrust-mysql:
    image: mysql:8.0.30
    # volumes:
    #   - ~/volumes/jhipster/DurantYoungerTrust/mysql/:/var/lib/mysql/
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=durantyoungertrust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#  dytrustllc-postgresql:
#    image: postgres:14.5
#    # volumes:
#    #   - ~/volumes/jhipster/DYTrustLLC/postgresql/:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=DYTrustLLC
#      - POSTGRES_PASSWORD=
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    # If you want to expose these ports outside your dev PC,
#    # remove the "127.0.0.1:" prefix
#    ports:
#      - 127.0.0.1:5432:5432
