# fly.toml app configuration file generated for green-frog-8526 on 2023-09-11T16:26:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-frog-8526"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
